server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/green?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Lah020112@
  thymeleaf:
    cache: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        hbm2ddl:
          import_files: classpath:DB/data.sql
  h2:
    console:
      enabled: true
