insert into product (product_name, description, price, quantity) values ('Dc - Sakura Fu', 'description', 61227, 97);
insert into product (product_name, description, price, quantity) values ('Wine - Jackson Triggs Okonagan', 'description', 161626, 430);
insert into product (product_name, description, price, quantity) values ('Soup - Beef, Base Mix', 'description', 14666, 356);
insert into product (product_name, description, price, quantity) values ('Potato - Sweet', 'description', 26549, 866);
insert into product (product_name, description, price, quantity) values ('Bread - Pita, Mini', 'description', 36182, 858);
insert into product (product_name, description, price, quantity) values ('Pickle - Dill', 'description', 1681, 486);
insert into product (product_name, description, price, quantity) values ('Lamb - Loin Chops', 'description', 158655, 996);
insert into product (product_name, description, price, quantity) values ('Rosemary - Fresh', 'description', 29089, 905);
insert into product (product_name, description, price, quantity) values ('Mustard - Individual Pkg', 'description', 88333, 397);
insert into product (product_name, description, price, quantity) values ('Sobe - Cranberry Grapefruit', 'description', 114504, 573);
insert into product (product_name, description, price, quantity) values ('Potatoes - Idaho 80 Count', 'description', 280827, 211);
insert into product (product_name, description, price, quantity) values ('Wine - Chateauneuf Du Pape', 'description', 236361, 46);
insert into product (product_name, description, price, quantity) values ('Cheese - Brie, Triple Creme', 'description', 177449, 420);
insert into product (product_name, description, price, quantity) values ('Veal - Chops, Split, Frenched', 'description', 158081, 736);
insert into product (product_name, description, price, quantity) values ('Turkey - Breast, Bone - In', 'description', 13918, 518);
insert into product (product_name, description, price, quantity) values ('Crackers - Trio', 'description', 169894, 854);
insert into product (product_name, description, price, quantity) values ('Tomato - Tricolor Cherry', 'description', 1524, 148);
insert into product (product_name, description, price, quantity) values ('Pasta - Penne, Rigate, Dry', 'description', 124598, 514);
insert into product (product_name, description, price, quantity) values ('Pumpkin - Seed', 'description', 171542, 846);
insert into product (product_name, description, price, quantity) values ('Momiji Oroshi Chili Sauce', 'description', 170191, 459);
insert into product (product_name, description, price, quantity) values ('Wine - Red, Lurton Merlot De', 'description', 167309, 864);
insert into product (product_name, description, price, quantity) values ('Ice Cream Bar - Oreo Sandwich', 'description', 199667, 68);
insert into product (product_name, description, price, quantity) values ('Kellogs All Bran Bars', 'description', 217859, 625);
insert into product (product_name, description, price, quantity) values ('Nut - Pistachio, Shelled', 'description', 255492, 204);
insert into product (product_name, description, price, quantity) values ('Snails - Large Canned', 'description', 191174, 176);
insert into product (product_name, description, price, quantity) values ('Breakfast Quesadillas', 'description', 274321, 714);
insert into product (product_name, description, price, quantity) values ('Beef - Rib Roast, Cap On', 'description', 129244, 120);
insert into product (product_name, description, price, quantity) values ('Tomato Paste', 'description', 167263, 580);
insert into product (product_name, description, price, quantity) values ('Bread - Olive Dinner Roll', 'description', 183149, 596);
insert into product (product_name, description, price, quantity) values ('Ice Cream - Turtles Stick Bar', 'description', 162358, 451);
insert into product (product_name, description, price, quantity) values ('Crackers - Trio', 'description', 253363, 357);
insert into product (product_name, description, price, quantity) values ('Chocolate Bar - Oh Henry', 'description', 275356, 511);
insert into product (product_name, description, price, quantity) values ('Pork - Backfat', 'description', 15846, 262);
insert into product (product_name, description, price, quantity) values ('Tomatoes Tear Drop Yellow', 'description', 5030, 22);
insert into product (product_name, description, price, quantity) values ('Ecolab - Hand Soap Form Antibac', 'description', 5620, 118);
insert into product (product_name, description, price, quantity) values ('Wine - Baron De Rothschild', 'description', 52903, 189);
insert into product (product_name, description, price, quantity) values ('Chicken - Diced, Cooked', 'description', 49007, 721);
insert into product (product_name, description, price, quantity) values ('Wine - Ej Gallo Sonoma', 'description', 29712, 657);
insert into product (product_name, description, price, quantity) values ('Bagelers - Cinn / Brown Sugar', 'description', 261024, 160);
insert into product (product_name, description, price, quantity) values ('Evaporated Milk - Skim', 'description', 279906, 977);
insert into product (product_name, description, price, quantity) values ('Longos - Assorted Sandwich', 'description', 293745, 794);
insert into product (product_name, description, price, quantity) values ('Neckerchief Blck', 'description', 80804, 638);
insert into product (product_name, description, price, quantity) values ('Nectarines', 'description', 49113, 731);
insert into product (product_name, description, price, quantity) values ('Pastry - Apple Large', 'description', 121130, 559);
insert into product (product_name, description, price, quantity) values ('Doilies - 12, Paper', 'description', 156636, 519);
insert into product (product_name, description, price, quantity) values ('Ecolab - Hobart Washarm End Cap', 'description', 279419, 765);
insert into product (product_name, description, price, quantity) values ('Oven Mitts 17 Inch', 'description', 66976, 644);
insert into product (product_name, description, price, quantity) values ('Pastry - Apple Large', 'description', 46132, 775);
insert into product (product_name, description, price, quantity) values ('Flour - Strong Pizza', 'description', 174038, 103);
insert into product (product_name, description, price, quantity) values ('Ecolab - Ster Bac', 'description', 4594, 361);
